workflows:
  android-workflow:
    name: Android Pipeline
    environment:
      android_signing:
        - keystore_reference
      vars:
        JAVA_HOME: /usr/lib/jvm/java-11-openjdk
      
    scripts:
      - name: Set up local.properties
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/local.properties"
      
      - name: Install dependencies
        script: |
          ./gradlew dependencies
      
      - name: Run tests
        script: |
          ./gradlew test
      
      - name: Run Kotlin linter
        script: |
          ./gradlew ktlintCheck
      
      - name: Build debug APK
        script: |
          ./gradlew assembleDebug
      
      - name: Build release APK
        script: |
          ./gradlew assembleRelease
    
    artifacts:
      - app/build/outputs/apk/debug/*.apk
      - app/build/outputs/apk/release/*.apk
      - app/build/outputs/mapping/release/mapping.txt
    
    publishing:
      email:
        recipients:
          - user@example.com
      google_play:
        credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
        track: internal  # Can be internal, alpha, beta, production
      
    triggering:
      events:
        - push
        - tag
        - pull_request
      branch_patterns:
        - pattern: 'main'
          include: true
        - pattern: 'develop'
          include: true
        - pattern: 'feature/*'
          include: true