workflows:
  kotlin_ci_cd:
    name: Kotlin CI/CD Pipeline
    environment:
      vars:
        GRADLE_CACHE: "true"
      android:
        ndk: latest
    scripts:
      # Install dependencies
      - echo "Installing dependencies..."
      - ./gradlew dependencies
      # Build the app
      - echo "Building the app..."
      - ./gradlew assembleRelease
      # Run unit tests
      - echo "Running tests..."
      - ./gradlew test
    artifacts:
      - build/outputs/**/*.apk
    publishing:
      google_play:
        credentials: $GOOGLE_PLAY_CREDENTIALS
        track: internal
