# codemagic.yaml
workflows:
  android-workflow:
    name: Android Pipeline
    environment:
      
      vars:
        JAVA_HOME: /Library/Java/JavaVirtualMachines/zulu-17.jdk/Contents/Home
        
      
    scripts:
      - name: Set up local.properties
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/local.properties"

      - name: Clean Gradle cache
        script: |
          ./gradlew clean
      
      - name: Install dependencies
        script: |
          ./gradlew dependencies
      
      - name: Run tests
        script: |
          ./gradlew test
      
      - name: Run Kotlin linter
        script: |
          ./gradlew ktlintCheck
      
      - name: Build debug APK
        script: |
          ./gradlew assembleDebug
      
      - name: Build release APK
        script: |
          ./gradlew assembleRelease
    
    artifacts:
      - app/build/outputs/apk/debug/app-debug.apk
      - app/build/outputs/apk/release/app-release.apk
      - app/build/outputs/mapping/release/mapping.txt
    
    publishing:
      email:
        recipients:
          - branu2000@gmail.com
      
    triggering:
      events:
        - push
        - tag
        - pull_request
      branch_patterns:
        - pattern: 'main'
          include: true
        - pattern: 'develop'
          include: true
        - pattern: 'feature/*'
          include: true