workflows:
  flutter-workflow:
    name: Flutter Workflow
    environment:
      flutter: stable
      vars:
        BUILD_MODE: release
    scripts:
      - name: Install dependencies
        script: flutter pub get
      - name: Run tests
        script: flutter test
      - name: Build APK
        script: flutter build apk --release
      - name: Build AppBundle
        script: flutter build appbundle --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
      - build/app/outputs/bundle/release/app-release.aab
    